### ISSUE TITLE
Proposal: GitHub Q&A Chatbot

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubiquibot-telegram#20]
- After getting this fixed https://github.com/microsoft/semantic-kernel/issues/2506 I tested it on the UbiquiBot repository. Seems like it could be useful to set up a q&a chatbot to help new hunters get productive on our repositories. 
- I haven't fully tested its accuracy yet so I want to test before turning this into a real bounty but it seems like a nice convenience tool if we can set up the bot once, and dynamically generate q&a for all of the repositories under the @ubiquity organization.
- I imagine a flow where we have a bot command that says something like "GitHub Q&A" and then they can select one of the repositories (dynamically loaded from our GitHub)

### Reference Screenshot From Microsoft GitHub Q&A App

<img width="862" alt="image" src="https://github.com/ubiquity/telegram-ubiquibot/assets/4975670/4331a08a-ed4a-4462-ad56-0c862b0d47dd">

**Comment by 0x4007** [comment]
- @sergfeldman cool find. Might be the future of `README.md`s. As you can see I've been researching it in passing. I'm sure there's some more cool things we can do with this kernel, including plugging it into the https://github.com/ubiquity/ubiquibot/issues/291 command.

**Comment by sergfeldman** [comment]
> As you can see I've been researching it in passing. I'm sure there's some more cool things we can do with this kernel

@pavlovcik Thank you, sounds great!
