### ISSUE TITLE
Post issue in Github on behalf of Telegram user

### ISSUE THREAD

**Issue by web4er** [ubiquity/ubiquibot-telegram#21]
Post the issue in Github on behalf of the user that sent the original message in telegram so that the posting user can get incentive.

Mapping between a user's telegram and GitHub will be added by https://github.com/ubiquity/telegram-ubiquibot/issues/4 , which is needed for this issue.

- context https://github.com/ubiquity/telegram-ubiquibot/pull/1#discussion_r1288727113

**Comment by web4er** [comment]
I think you will be reviewing time and adding priority so that the price can be applied. @pavlovcik

**Comment by 0x4007** [comment]
Perhaps the repo config is invalid? It's hard to tell from my phone. Please feel free to price this issue @web4er

**Comment by 0x4007** [comment]
The old priority levels should be renamed to the updated names. This is not easy for me to do from mobile though.

**Comment by seprintour** [comment]
> Post the issue in Github on behalf of the user that sent the original message in telegram so that the posting user can get incentive.

This means the time estimate feature of the bot would not be used, because its not allowing contributors alter labels

**Comment by 0x4007** [comment]
> > Post the issue in Github on behalf of the user that sent the original message in telegram so that the posting user can get incentive.
> 
> 
> 
> This means the time estimate feature of the bot would not be used, because its not allowing contributors alter labels

Should be fine

**Comment by seprintour** [comment]
> Permit generation skipped since this issue didn't qualify as bounty

Here @pavlovcik
