### ISSUE TITLE
"Post on Behalf of Users" Review Adjustments - II

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubiquibot-telegram#24]
Related https://github.com/ubiquity/telegram-ubiquibot/issues/23

- [ ] The bot should not post real messages to the group chat, but instead post "private messages" inside of the group chat, which is only visible to the person who invoked the bot. I've seen this Telegram bot capability with bots that send new users private CAPTCHAs when they join large group chats. The user is able to interact with the bot in a private manner inside of the context of the group chat (nobody else sees the messages)
- [ ] Enable a "force task to write to GitHub" capability by directly tagging the bot inside of the message to force recording it on GitHub (this is useful for edge cases where the bot doesn't automatically pick up a message as a task)

**Comment by seprintour** [comment]
> Do you have any updates @seprintour? If you would like to release the bounty back to the DevPool, please comment `/stop` Last activity time: Sun Sep 10 2023 18:35:33 GMT+0000 (Coordinated Universal Time)

Highly dependent on #25

**Comment by seprintour** [comment]
> Do you have any updates @seprintour? If you would like to release the bounty back to the DevPool, please comment `/stop` Last activity time: Sun Sep 17 2023 14:06:17 GMT+0000 (Coordinated Universal Time)

A PR should be attached before end of day

**Comment by seprintour** [comment]
> * I've seen this Telegram bot capability with bots that send new users private CAPTCHAs when they join large group chats.

@pavlovcik  I did some more research and inline mode is not going to cut it for our implementation.

Right now, there is no way of having a private chat inside of a public group chat.. Captcha bot either uses private chat or posts the button publicly and deletes it after a timeout or the user clicks it

**Comment by seprintour** [comment]
I'd come back here
