### ISSUE TITLE
Update README.md - September 2023

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubiquibot-telegram#26]
@seprintour you should update and add all the setup steps in a README, particularly the bot settings on `@BotFather`, so that future developers can set up and work on the bot.

**Comment by seprintour** [comment]
I think I have all the stages there right now, no need for complex @BotFather setup, adding commands is automated now

Follow the steps and it would work

**Comment by 0x4007** [comment]
> [Inline mode](https://core.telegram.org/bots/inline) is currently disabled for UbiquiBot @UbiquityDAO_bot.
> i enable this right?

> Yes, would be useful for the next issue
> Perhaps there'd be a way to enable it programatically

These are the details I was suggesting that should be added.

**Comment by seprintour** [comment]
> These are the details I was suggesting that should be added.

Wasn't in use at this point, would have added it once the inline feature is complete

**Comment by seprintour** [comment]
#24

**Comment by PhantomCracker** [comment]
Do we still need to do something here? Or is this specific issue for @seprintour ?
