### ISSUE TITLE
Automated Supabase Migrations

### ISSUE THREAD

**Issue by seprintour** [ubiquity/ubiquibot-telegram#29]
### Problem:
Currently, managing database migrations in Supabase requires manual execution of migration scripts. This process can be error-prone, time-consuming, and lacks the efficiency needed for modern development workflows. As our project grows, the need for automation becomes increasingly evident to ensure seamless database updates.

### Proposed Solution:
I propose automating Supabase migrations by leveraging GitHub Deployment workflows. This enhancement will significantly improve our development process, making database schema updates a hassle-free and reliable part of our continuous integration pipeline.

Here is a working example of automated migration on supabase: https://github.com/ubiquity/ubiquibot/blob/development/.github/workflows/build.yml

We can copy that over, modify the secrets name and make some minor adjustments

File path to be migrated: https://github.com/ubiquity/ubiquibot-telegram/tree/development/supabase/migrations

Supabase Project ID Secret: `SUPABASE_PROJECT_ID`
Supabase Access Token: `SUPABASE_PROJECT_KEY`
Supabase DB Password: `SUPABASE_DB_PASSWORD`

**Comment by seprintour** [comment]
Now, somethings up here.. It's not down or bad, it's just irregular.

Hmm

**Comment by 0x4007** [comment]
Well it combined your rewards for identifying the issue and fixing it. It just gave you a lot of rewards for issue creation, which we will eventually limit to the bounty price. I think it looks fine. 

I also got paid $0.2 for saying "look fine" lol

**Comment by seprintour** [comment]
> Well it combined your rewards for identifying the issue and fixing it. It just gave you a lot of rewards for issue creation, which we will eventually limit to the bounty price. I think it looks fine.

It added it in the permit comment but when i try to claim, it does not add the creator amount

I traced it down to this line: https://github.com/ubiquity/ubiquibot/blob/f41c03691d5849e546db8bfb62b907122294a820/src/handlers/payout/action.ts#L415

It's supposed to be `priceInEth` not `assigneeReward.reward[0].priceInEth`

**Comment by 0x4007** [comment]
You can turn your comment into a new issue and get around to it when you are not actively working on 2-3 tasks or whatever. You get paid for identifying the issue.

**Comment by 0x4007** [comment]
@seprintour its in your best interest to file the issue asap so that you can take credit for filing it. Even if you end up not working on it the incentives should make it more profitable for you to identify and file issues asap. Otherwise somebody else can make the issue and you don't get credit.
