### ISSUE TITLE
Telegram Database

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubiquibot-telegram#3]
We must be able to associate which Telegram channel/topic goes to which GitHub repository. For example, we add the same bot to three different telegram groups, the admin should be able to configure which repository the bot will create issues at. [Reference](https://github.com/ubiquity/telegram-ubiquibot/pull/1/files#r1288734594).

### Required Capabilities 
- [x] Set up database
- [x] Set up interface on bot for Telegram group admins to configure. 
- [x] Associating Telegram handle with GitHub handle. [Reference](https://github.com/ubiquity/telegram-ubiquibot/pull/1/files#r1288727113). Used with #4

**Comment by seprintour** [comment]
I think we need this before the 0Auth

**Comment by seprintour** [comment]
This took longer than expected, almost done here

Should've been a <1 Day task

**Comment by 0x4007** [comment]
Reopened because this did not pass review 
- https://github.com/ubiquity/telegram-ubiquibot/pull/10#issuecomment-1680507434

**Comment by seprintour** [comment]
> Reopened because this did not pass review
> 
> * [Link database #10 (comment)](https://github.com/ubiquity/telegram-ubiquibot/pull/10#issuecomment-1680507434)

It passed review, just error `Uncaught ReferenceError: SUPABASE_URL is not defined`..

You'd have to link Ubiquity Supabase to Cloudflare worker and that'd be fixed @pavlovcik

**Comment by 0x4007** [comment]
This is the review

<img width="330" alt="Screenshot 2023-08-16 at 21 47 38" src="https://github.com/ubiquity/telegram-ubiquibot/assets/4975670/0151aafa-2b5e-4402-ae04-8d5662d67d85">

**Comment by seprintour** [comment]
> This is the review
> 
> <img alt="Screenshot 2023-08-16 at 21 47 38" width="330" src="https://user-images.githubusercontent.com/4975670/261011924-0151aafa-2b5e-4402-ae04-8d5662d67d85.png">

Oh okay
