### ISSUE TITLE
Issue to verify repo

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubiquibot-telegram#31]
UbiquiBot, [Sep 21, 2023 at 22:18]
Please provide the URL of repository you want to link to this forum.

 アレクサンダー.eth | U B I Q U I T Y, [Sep 21, 2023 at 22:19]
https://github.com/ubiquity/pay.ubq.fi

 UbiquiBot, [Sep 21, 2023 at 22:19]
Invalid GitHub URL. Please provide a valid GitHub repository URL.

Examples:
- https://github.com/user/repo
- https://www.github.com/user/repo

**Comment by seprintour** [comment]
Wrong label here, and what's the issue exactly.. https://github.com/ubiquity/pay.ubq.fi isn't a valid repo?

**Comment by 0x4007** [comment]
The regex parser is probably getting confused from the periods in the repo name.
