### ISSUE TITLE
Misc Improvements

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubiquibot-telegram#34]
1. I changed the bot admin title and it posted the welcome message again https://t.me/UbiquityDAO/1/31176
2. I'm unsure how to register the general topic https://t.me/UbiquityDAO/1/31178 - update: the bot should explain that it's already added and to configure in the settings. 
3. UI no longer usable after several added topics. It no longer responds to button presses:

![image](https://github.com/ubiquity/ubiquibot-telegram/assets/4975670/12dfed17-acb0-4597-b3cd-b56c773c8aa4)

4. Renamed `fundraising` to `partnerships` in https://t.me/UbiquityDAO/29361 and it's not being updated in bot UI

> Here is your forum: Fundraising 
What do you want to do?

**Comment by seprintour** [comment]
PR attached

**Comment by devpanther** [comment]
> #### Reviewer Rewards 
> 
> ### [ **seprintour: [ CLAIM 10.5 WXDAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMTA1MDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiIxMjg5NDkzMTgzMDQyMTQ4ODIxNDU3NDA2MjI5MjA3ODQyMTUzMzQ4OTI5ODU5OTM3MTMzMzAzMDIwNTE4NzE5NTY0MjQ3OTYxNDcwMyIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4MzYyMzMzODA0NmIxMDFlY0VjNzQxRGU5QzM1OTRDQzIxNzZmMzlFNSIsInJlcXVlc3RlZEFtb3VudCI6IjEwNTAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHgwY2FkMmQ3NzA1YjIzMjVkYzEzOGQ5ZWNlNDY1ODA0ZWRkMDFkNDhhY2QzZTBhNzlmZDgxYzdiMGU0ZTJjZGExNzlhODY5ZTMwNDYxZTU1ZjRhNDg4NGQzNjJlOGU5YzFiM2Y3YjBlYWFjNmViNDQ2MTE5MDc4MzY3NThmNDk4YTFiIn0=&network=100)
> 

Yet, another assignee issue here.. Assignee object should be typed so using it as a string would error

**Comment by seprintour** [comment]
@pavlovcik can you check if this permit is on the logs too please

**Comment by seprintour** [comment]
@pavlovcik Can i get this permit URL from the DB, it was not posted here

**Comment by 0x4007** [comment]
> @pavlovcik Can i get this permit URL from the DB, it was not posted here

In your dm
