### ISSUE TITLE
UbiquiBot Logs: Error Notifications

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubiquibot-telegram#37]
- We should have a webhook that we can post arbitrary messages to. 
- We must be able to configure where it dumps the arbitrary messages to (which group chat.)
- Requires some type of basic auth system, or else anybody can spam any group the bot is in. 

Inspiration: we rolled out a new update to UbiquiBot and there are errors with all the configs so its down on every repo basically. It would be ideal to receive push notifications that the bot failed to run so that everybody is alerted to fix the problem. Apparently its been about a full day for the team to diagnose (not great because it was me and I'm trying to not be on GitHub these days)

**Comment by b4s36t4** [comment]
So if I understand the problem correctly.. 

Whenever bot failed to run a command, it should send a detailed about the fail to subscribed chats? 

Webhook is to send announcements like notifications about the downtime? So that all subscribers are notified and updated about the bot real-time. 

Am I correct here?

**Comment by seprintour** [comment]
> - Requires some type of basic auth system, or else anybody can spam any group the bot is in. 

signed and validated JWT should cut the auth right? @pavlovcik

It'd also contain a secret that'd be stored on both ubiquibot env and the telegram bot's env.

I'm thinking we should make the group an env too, except we're making it a feature for any group to make use of.

**Comment by seprintour** [comment]
Rfc

**Comment by seprintour** [comment]
> I'm thinking we should make the group an env too, except we're making it a feature for any group to make use of.

rfc on this

**Comment by 0x4007** [comment]
I don't understand what you mean but this should be generalized for other purposes outside of just error logs in the future.

> - We should have a webhook that we can post arbitrary messages to.
> - We must be able to configure where it dumps the arbitrary messages to (which group chat.)

**Comment by seprintour** [comment]
> * We must be able to configure where it dumps the arbitrary messages to (which group chat.)

This is what i mean, should we add the id of the group chat it is posting to as an env or make it an admin menu so any one using the bot for their group can make use of this feature.

**Comment by 0x4007** [comment]
> make it an admin menu so any one using the bot for their group can make use of this feature.

Seems more useful

**Comment by seprintour** [comment]
> Seems more useful

Oh, that'd take alot more than 4 hours as the groups need to generate jwt using the admin panel and perhaps even create their own secrets automatically from the menu

**Comment by 0x4007** [comment]
Lets do the simple way then. Env var...or cant you just generate an "admin panel" in the bot private chat?

**Comment by seprintour** [comment]
> or cant you just generate an "admin panel" in the bot private chat?

Yea, that was what i was referring to.. i'd take a lot more time, i would just plug it into the existing admin menu and then create functions to generate, store/keep track and validate across several groups.

I'd just use an env for now, since its just meant for ubiquity org

**Comment by seprintour** [comment]
PR ready to review @pavlovcik

**Comment by 0x4007** [comment]
Ping https://GitHub.com/ubiquity/ubiquibot/issues/803

**Comment by seprintour** [comment]
😳

**Comment by seprintour** [comment]
There's logs to diagnose this issue right? @pavlovcik

**Comment by 0x4007** [comment]
> https://GitHub.com/ubiquity/ubiquibot/issues/803

Yes there are logs but the public logs app isn't working so I would need to add you to the supabase project directly to view I believe. 

I do see the logs for it claiming to generate all of the permits, it just doesn't seem to actually post them. For example, I found the following three associated with this issue:

1. Generated permit2 url: https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiNTEwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjU1MDQ3MjYyNjU2MTMwNDg2NjI1OTA1ODY1NjM1NTU1MDAxNzQ5NTgxNjA1OTAyMTA1NDg2Mjk3MjgxOTQyNzUzODc2NTYzNzQwODg1IiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHhDZWUzM0M5ODQxMERFYmU2N0EzMTlDYjk0RjM5ZTQwMzQzNURmMzE5IiwicmVxdWVzdGVkQW1vdW50IjoiNTEwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4Zjg3Y2E0NTgzQzc5MjIxMmU1MjcyMGQxMjdFN0UwQTM4QjgxOGFEMSIsInNpZ25hdHVyZSI6IjB4N2Y1OGE3NDhiYjZkMmU2NGRmNzMwY2RmN2M1NzJhYzk0MTVlMjZkNzY3ZmQxMjY0YzJjMjNmYmFhNzE0YzBjYjY3NTc4NDFhOWM4MDFlMGIwN2U3ZGJiZWE1MGU5NjVhYWQ0MTgzNTdiNzQyNDc4NTY4ZGI4NTg1ZDY5MTYzYjgxYyJ9&network=100
2. Generated permit2 url: https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMjAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiNDk1NTE0MDIwMDg1NDE4NDkyNTE2NTMwNzY1OTM3MTY1NDU0NjUyNzI0NTEzMTg4Nzk4MjQ1NDcyMjEwNzE1MjU3NzgxNDc5OTMxMzgiLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweDM2MjMzMzgwNDZiMTAxZWNFYzc0MURlOUMzNTk0Q0MyMTc2ZjM5RTUiLCJyZXF1ZXN0ZWRBbW91bnQiOiIyMDAwMDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweGY4N2NhNDU4M0M3OTIyMTJlNTI3MjBkMTI3RTdFMEEzOEI4MThhRDEiLCJzaWduYXR1cmUiOiIweDBkYzU2ZTQyM2Q0NmRmY2NmOTA0MWZiOWQwZDA4ZjMyMGIzMzE1N2RjMGVkMDgwNmQ2ZjEyNGI1ZmQ2ZjAzOWU0MTg2MWQzMjhjNGY4OWVkNTZiY2ZmMzc2ODMzMTczYjc1ZjAzYTU4ZTJkMzc2OTU0NTMwN2NkMmI2ZDE1MmRhMWMifQ==&network=100
3. Generated permit2 url: https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiNDA4MDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiIzMTU2MDY3MDg5MjI3MjIxMzQxMDAzNjU4MDYxNzE3OTk1NjE1NzQyOTMxNjEwNjkzMDA4NjM3ODIzNTE1MzMxMjk2NzY5ODUzMjU0IiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHg0MDA3Q0UyMDgzYzdGM0UxODA5N2FlQjNBMzliYjhlQzE0OWEzNDFkIiwicmVxdWVzdGVkQW1vdW50IjoiNDA4MDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweGY4N2NhNDU4M0M3OTIyMTJlNTI3MjBkMTI3RTdFMEEzOEI4MThhRDEiLCJzaWduYXR1cmUiOiIweDk3NzIwN2M4YzIwMmViODgwY2RjMzAyMjAzYjZlZjhhOTBmMTg3MGIyMTUwNjRjNWRlNmJhODRjZjZlNjc2MWM2NmViNWU3OWM3N2JiNGJiZDZjODc3NjdiNGQ3ZDIwOTgwODkwYWM3NGY4ZmY1MGI4NWE5OTI3ODAxY2FiYWJlMWIifQ==&network=100

**Comment by b4s36t4** [comment]
https://github.com/ubiquity/ubiquibot-telegram/issues/37#issuecomment-1732500039

I can claim right?? 😂

**Comment by seprintour** [comment]
I think the permits are valid on this url you posted
