### ISSUE TITLE
OAuth to associate Telegram and GitHub handle

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubiquibot-telegram#4]
- Create a simple OAuth Telegram bot app that will associate one's Telegram and GitHub handle together, then save it to our #3 
- Conversation context: https://github.com/ubiquity/telegram-ubiquibot/pull/1#discussion_r1288727113

**Comment by 0x4007** [comment]
We need this for a marketing push as well. We're promoting at ethcon.kr hackathon (1 September) to try and get partners and more developers in the DevPool. We are giving out some bags and tee shirts with QR codes that will  go to a landing page to onboard them into the DevPool. It could be very useful to capture their Telegram + GitHub in this flow as well.

**Comment by seprintour** [comment]
> Do you have any updates @seprintour? If you would like to release the bounty back to the DevPool, please comment `/stop` Last activity time: Sat Aug 12 2023 08:14:01 GMT+0000 (Coordinated Universal Time)

soon

**Comment by 0x4007** [comment]
> > Do you have any updates @seprintour? If you would like to release the bounty back to the DevPool, please comment `/stop` Last activity time: Sat Aug 12 2023 08:14:01 GMT+0000 (Coordinated Universal Time)
> 
> soon

You should have a draft pull request opened as soon as you start working on issue.

**Comment by seprintour** [comment]
> You should have a draft pull request opened as soon as you start working on issue

It depends on #15, I needed a clean working commit.. not something that'd show both commits in one PR.

That's the reason i tried to merge the database issue the last time

**Comment by 0x4007** [comment]
> > You should have a draft pull request opened as soon as you start working on issue
> 
> 
> 
> It depends on #15, I needed a clean working commit.. not something that'd show both commits in one PR.
> 
> 
> 
> That's the reason i tried to merge the database issue the last time

You can have two branches, with two pull requests, open simultaneously from your fork. I don't understand your point.

**Comment by seprintour** [comment]
> You can have two branches, with two pull requests, open simultaneously from your fork. I don't understand your point.

Mu point is, if i create a new branch from another branch that is still under review.. changes i'd make in the branch it is created from would not automatically reflect and it shows commit from that branch as well.

I usually like it clean and no merge conflicts when i am done, but i created a draft already.. working on it

**Comment by 0x4007** [comment]
> changes i'd make in the branch it is created from would not automatically reflect and it shows commit from that branch as well.

There's git rebase for this. This is very simple to do with git graph extension in vscode 

I think git has been around long enough to have features for most of these common issues.

**Comment by seprintour** [comment]
@pavlovcik labels issue here

**Comment by 0x4007** [comment]
That's unexpected that without label access control you were still able to generate a payment permit.

**Comment by seprintour** [comment]
> That's unexpected that without label access control you were still able to generate a payment permit.

Oh, I just had to delete the stale label and edit it.. I don't think it was really a vulnerability, just me having access to edit label name and color even though I can't alter them  on issues

**Comment by 0x4007** [comment]
> > That's unexpected that without label access control you were still able to generate a payment permit.
> 
> Oh, I just had to delete the stale label and edit it.. I don't think it was really a vulnerability, just me having access to edit label name and color even though I can't alter them on issues

That's a really interesting attack vector! So you can get around access control on labels by editing other labels already on the issue?

**Comment by seprintour** [comment]
> That's a really interesting attack vector! So you can get around access control on labels by editing other labels already on the issue?

Yea, deleting and updating labels should circumvent the access control blocking

**Comment by 0x4007** [comment]
This means that our approach could be flawed, unless we can detect this specific behavior and protect against it. For example, if anybody but an `admin` or `billing_manager` updates labels, then an `admin` or `billing_manager` must manually re-allow automatic payment permit generation.

**Comment by seprintour** [comment]
> This means that our approach could be flawed, unless we can detect this specific behavior and protect against it.

I'd take up the issue and block edit label event too with access control

**Comment by 0x4007** [comment]
> > This means that our approach could be flawed, unless we can detect this specific behavior and protect against it.
> 
> I'd take up the issue and block edit label event too with access control

I'd prefer that you focus on re-enabling support for Telegram group topics for the bot, as that was not correctly implemented in your previous bounty. Normally I would re-open the issue but I assumed you were going to address that pretty soon. 

https://github.com/ubiquity/telegram-ubiquibot/pull/17#issuecomment-1712892726

**Comment by seprintour** [comment]
> as that was not correctly implemented in your previous bounty

I think it was gotten wrong from the database feature..

I'm trying to look for a way to list topics when editing group details.. If we can't list topics then it won't really work
