### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubiquibot-telegram#9]
Leverage the existing template to convert to a pure TypeScript codebase (no JavaScript and no `any` typings!)

**Comment by baibhavKumar1** [comment]
@pavlovcik , what are the token and github_pat for testing? 
{
  "token": "",
  "webhook": "/endpoint",
  "secret": "QUEVEDO_BZRP_Random_String_52",
  "openai_api_key": "",
  "github_pat": "",
  "default_priority": "Priority: 0 (Normal)"
}

**Comment by 0x4007** [comment]
@seprintour would know best but I'm assuming you generate your own personal access token for your GitHub account. The "token" property I assume is for your telegram bot token.

**Comment by seprintour** [comment]
> @seprintour would know best but I'm assuming you generate your own personal access token for your GitHub account. The "token" property I assume is for your telegram bot token.

Yes, @Wholesomebruh Use your github_pat for testing and create a bot with telegram BotFather to get the token

**Comment by baibhavKumar1** [comment]
Converted the code, but unable to test, as hooks are required in bot.

**Comment by 0x4007** [comment]
I'm not sure what "hooks" means. @seprintour any remarks?

**Comment by seprintour** [comment]
> I'm not sure what "hooks" means. @seprintour any remarks?

I'm not sure too, sounds weird.. he should attach a PR anyway so we can see it

**Comment by Steveantor** [comment]
@pavlovcik is the bot supposed to generate a link?

**Comment by 0x4007** [comment]
> @pavlovcik is the bot supposed to generate a link?

Maybe the bot rugged you from the [debt feature](https://github.com/ubiquity/ubiquibot/issues/439#issue-1776797456)? due to https://github.com/ubiquity/ubiquibot/issues/268#issuecomment-1585532148 but didn't properly post the comment because the feature was completed during the completion of the previous issue. 

Example comment https://github.com/ubiquity/ubiquibot/issues/272#issuecomment-1674411163

@0xcodercrane is there anything we can do for @Steveantor for this? What is the proper solution?

**Comment by cuddle-dev** [comment]
@Steveantor heres your claim link.

**Comment by cuddle-dev** [comment]
The best thing is to have a log monitoring system to figure out why the bot didn't work sometimes.
The main feature of log monitoring system is search for the past things by key.
Even if we implement logging system using supabase, it will not help me to debug until we have fancy search feature.
But we don't have the right way to figure out why the bot didn't work as long as @pavlovcik don't want to pay for the logging system.

**Comment by 0x4007** [comment]
Supabase logging soon™️. Searching is easy in SQL

**Comment by 0xcodercrane** [comment]
> Supabase logging soon™️. Searching is easy in SQL

it would be easy to you, but not for me lol

**Comment by seprintour** [comment]
@Steveantor did you test that this works before pushing..

I see you changed all the cloudflare environment variables to `process.env`.. It does not work like that

You should've tested it

**Comment by 0x4007** [comment]
> I see you changed all the cloudflare environment variables to `process.env`.. It does not work like that

I had no idea either. I suppose a hotfix to find-and-replace to remove instances of that should be pretty straightforward.

**Comment by seprintour** [comment]
> > I see you changed all the cloudflare environment variables to `process.env`.. It does not work like that
> 
> I had no idea either. I suppose a hotfix to find-and-replace to remove instances of that should be pretty straightforward.

I am adding that to my next PR, i am changing the codes from my reverted PR to typescript and testing to make sure nothing broke

**Comment by Steveantor** [comment]
> @Steveantor did you test that this works before pushing..
> 
> I see you changed all the cloudflare environment variables to `process.env`.. It does not work like that
> 
> You should've tested it

I needed to declare globals for typescript, I'll push a hotfix

**Comment by seprintour** [comment]
> > @Steveantor did you test that this works before pushing..
> > I see you changed all the cloudflare environment variables to `process.env`.. It does not work like that
> > You should've tested it
> 
> I needed to declare globals for typescript, I'll push a hotfix

Thank you ser, can i just copy the global ts file.. Alot has changed in those functions where the env were used so it would be a merge conflict

I already fixed it in mine but i see you made a file for it, i'd just pull in that file

**Comment by Steveantor** [comment]
> > > @Steveantor did you test that this works before pushing..
> > > I see you changed all the cloudflare environment variables to `process.env`.. It does not work like that
> > > You should've tested it
> > 
> > 
> > I needed to declare globals for typescript, I'll push a hotfix
> 
> Thank you ser, can i just copy the global ts file.. Alot has changed in those functions where the env were used so it would be a merge conflict
> 
> I already fixed it in mine but i see you made a file for it, i'd just pull in that file

yeah sure, I'll ping you once the CI passes
